### ISSUE TITLE
项目中spring boot和Spring Cloud 版本对应关系

### ISSUE THREAD

**Issue by yanglin1501804006** [macrozheng/springcloud-learning#1]
你好：
我在Spring Cloud Greenwich.SR2 【源码位置：https://github.com/spring-cloud/spring-cloud-release/releases/tag/vGreenwich.SR2】
的 spring-cloud-starter-parent的pom.xml中查看有：

<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.6.RELEASE</version>
	</parent>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-parent</artifactId>
	<version>Greenwich.SR2</version>
	<name>spring-cloud-starter-parent</name>
	<description>Spring Cloud Starter Parent</description>
也就是说Greenwich.SR2 版本基于 spring boot 2.1.6 .

我的疑问是：
1：当我使用Greenwich.SR2 版本的时候，我的spring boot 版本是必须大于等于2.1.6 版本吗？
2：自然，该项目中使用 Greenwich.SR2 版本,spring boot 是 2.1.7 能否作为问题1的答案呢？

**Comment by macrozheng** [comment]
你可以看下这个[SpringCloud整体架构概览](https://juejin.im/post/5d764f05e51d4561fb04bfd7)，SpringCloud Greenwich 版本和SpringBoot 2.1.x版本都是兼容的。
