### ISSUE TITLE
jwk-set-uri 能否从注册中心获取？

### ISSUE THREAD

**Issue by isegon** [macrozheng/springcloud-learning#12]
示例代码中 jwk-set-uri 的地址是写死的，对于微服务多实例不友好，
能否改成通过注册中心获取？

**Comment by yumindayu** [comment]
貌似jwt-set-uri不支持注册中心负责均衡的方式获取，比如 lb://这种，但是可以通过设置public-key-location将公钥以文件的形式放到本地，避免通过jwt-set-uri单点的故障

**Comment by yumindayu** [comment]
看源码public-key-location的优先级高于jwk-set-uri
