### ISSUE TITLE
token正常失效后 再访问网关 直接返回401不走拦截器

### ISSUE THREAD

**Issue by zhangchaoyanggit** [macrozheng/springcloud-learning#15]
ServerAuthenticationEntryPoint 这个拦截器没走，网关直接响应401  不知道该从哪拦截了。。。

**Comment by yanzhisishui** [comment]
> ServerAuthenticationEntryPoint 这个拦截器没走，网关直接响应401 不知道该从哪拦截了。。。

你好，我也是这种情况，直接返回的 401 请问能指点一下问题出在哪吗？感激不尽
![image](https://user-images.githubusercontent.com/44022031/126030997-eb126149-9b32-49af-89d3-d8b2e5017221.png)

**Comment by xiaoyaojian** [comment]
> ，我也是这种情况，直接返回的 401 请问能指点一下问题出在哪吗？感激不尽

你如果完全按照教程写的话，那client_id应该是client-app，不是client_app

**Comment by cunzhiwang** [comment]
可以在yaml添加这个配置logging.level.org.springframework.security: DEBUG，查看具体的日志

**Comment by cunzhiwang** [comment]
> > ServerAuthenticationEntryPoint 这个拦截器没走，网关直接响应401 不知道该从哪拦截了。。。
> 
> 你好，我也是这种情况，直接返回的 401 请问能指点一下问题出在哪吗？感激不尽 ![image](https://user-images.githubusercontent.com/44022031/126030997-eb126149-9b32-49af-89d3-d8b2e5017221.png)

可以在yaml添加这个配置logging.level.org.springframework.security: DEBUG，查看具体的日志
