### ISSUE TITLE
客户端的yml配置: spring.oauth2.resource.jwt.key-uri作用是什么?

### ISSUE THREAD

**Issue by fengjunzixian** [macrozheng/springcloud-learning#2]
1   注释了客户端启动不起来,在网上找了下解释说: "解析jwt令牌所需要密钥的地址,",

**Comment by fengjunzixian** [comment]
2   学习了下OAUTH2, OAUTH2是一种认证协议,如果单独使用OAUTH做登录,配合存储策略如JWT,REDIS可用于单点登录,也就是说单点登录必须设置存储策略,JWT的单点登录和普通的cas单点登录的优势取舍是什么.

**Comment by gitzhang** [comment]
不值得能否不使用keypair？不想使用jwk-set-uri配置

**Comment by yumindayu** [comment]
作用是向授权服务器获取公钥，用公钥来解密token
