### ISSUE TITLE
是否可以不使用redis

### ISSUE THREAD

**Issue by 2540461056** [macrozheng/springcloud-learning#28]
如果不需要人为让token失效的功能，是否可以去掉redis? 我尝试去掉redis，但是对api的保护也没有了，请问应该如何更改代码？

**Comment by cunzhiwang** [comment]
> 

哪一个模块呢

**Comment by 2540461056** [comment]
你好大佬，
&nbsp; &nbsp; &nbsp;我之前是想问redis存储url和角色的哪里，能不能不用redis；因为我看别人都是用redis存token的；


&nbsp; &nbsp; &nbsp;现在我发现，如果资源服务，使用的url中带有{}型参数，比如/get/user/{1}；那么gateway鉴权的时候就很麻烦了，
因为{1}这个参数不一定在最后，也可能在中间比如/get/{2}/car；
&nbsp; &nbsp; &nbsp;这种情况下，有什么办法可以很好的兼容这个问题吗？


&nbsp; &nbsp; &nbsp;另外您这个demo很好，很多点都考虑到了，比如过滤器、token增强什么的。




Ll
***@***.***



&nbsp;
