### ISSUE TITLE
config-server不能刷新消息总线的bug

### ISSUE THREAD

**Issue by yang3737** [macrozheng/springcloud-learning#4]
在使用消息总线的时候，config-server还需要一个依赖包<artifactId>spring-boot-starter-web</artifactId>

**Comment by 54dujianchao** [comment]
同样的问题 
在这一节 http://www.macrozheng.com/#/cloud/bus 
调用注册中心的接口刷新所有配置：http://localhost:8904/actuator/bus-refresh 不起作用

**Comment by 54dujianchao** [comment]
> 在使用消息总线的时候，config-server还需要一个依赖包spring-boot-starter-web

加上了也不行

**Comment by 54dujianchao** [comment]
不好意思  解决了 ，没注意到 ，要用post请求 😅
顺便说一下 ，教程很好 ，入门很容易
